server:
  port: 9899
spring:
    application:
      name: calculate-service
    cloud:
      consul:
        host: 192.168.0.15
        port: 8500
        discovery:
          healthCheckInterval: 15s
          instance-id: calculate-service

logging:
    level:
      com:
        bzdepot:
          communal:
            mapper: debug
#请求和响应GZIP压缩支持
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

management:
  endpoint:
    health:
      show-details: always

